export default function ClinicalFormsTable() {
    const tableData = [
      {
        title: "Ethics Committee and Permission to Conduct Clinical Trial",
        rows: [
          ["CT-01", "APPLICATION FOR REGISTRATION/RENEWAL OF ETHICS COMMITTEE RELATING TO CLINICAL TRIAL OR BIOAVAILABILITY AND BIOEQUIVALENCE STUDY OR BIOMEDICAL HEALTH RESEARCH", "CT-02", "GRANT OF REGISTRATION OF ETHICS COMMITTEE RELATING TO CLINICAL TRIAL OR BIOAVAILABILITY AND BIOEQUIVALENCE STUDY"],
          ["CT-01", "APPLICATION FOR REGISTRATION/RENEWAL OF ETHICS COMMITTEE RELATING TO CLINICAL TRIAL OR BIOAVAILABILITY AND BIOEQUIVALENCE STUDY OR BIOMEDICAL HEALTH RESEARCH", "CT-03", "GRANT OF REGISTRATION OF ETHICS COMMITTEE RELATING TO BIOMEDICAL HEALTH RESEARCH"],
          ["CT-04", "APPLICATION FOR GRANT OF PERMISSION TO CONDUCT CLINICAL TRIAL OF NEW DRUG OR INVESTIGATIONAL NEW DRUG", "CT-06", "PERMISSION TO CONDUCT CLINICAL TRIAL OF NEW DRUG OR INVESTIGATIONAL NEW DRUG"],
          ["CT-05", "APPLICATION FOR GRANT OF PERMISSION TO CONDUCT BIOAVAILABILITY OR BIOEQUIVALENCE STUDY", "CT-07", "PERMISSION TO CONDUCT BIOAVAILABILITY OR BIOEQUIVALENCE STUDY OF NEW DRUG OR INVESTIGATIONAL NEW DRUG"],
          ["CT-08", "APPLICATION FOR REGISTRATION/RENEWAL OF BIOAVAILABILITY OR BIOEQUIVALENCE STUDY CENTRE", "CT-09", "GRANT OF REGISTRATION OF BIOAVAILABILITY OR BIOEQUIVALENCE STUDY CENTRE"],
        ],
      },
  
      {
        title: "Test Licences",
        rows: [
          ["CT-10", "APPLICATION FOR GRANT OF PERMISSION TO MANUFACTURE NEW DRUG OR INVESTIGATIONAL NEW DRUG FOR CLINICAL TRIAL OR BIOAVAILABILITY OR BIOEQUIVALENCE STUDY OR FOR EXAMINATION, TEST AND ANALYSIS", "CT-11", "PERMISSION TO MANUFACTURE NEW DRUG OR INVESTIGATIONAL NEW DRUG FOR CLINICAL TRIAL, BIOAVAILABILITY OR BIOEQUIVALENCE STUDY OR FOR EXAMINATION, TEST AND ANALYSIS"],
          ["CT-12", "APPLICATION FOR GRANT OF PERMISSION TO MANUFACTURE FORMULATION OF UNAPPROVED ACTIVE PHARMACEUTICAL INGREDIENT FOR TEST OR ANALYSIS OR CLINICAL TRIAL OR BIOAVAILABILITY OR BIOEQUIVALENCE STUDY", "CT-14", "PERMISSION TO MANUFACTURE FORMULATION OF UNAPPROVED ACTIVE PHARMACEUTICAL INGREDIENT FOR TEST OR ANALYSIS OR CLINICAL TRIAL OR BIOAVAILABILITY OR BIOEQUIVALENCE STUDY"],
          ["CT-13", "APPLICATION FOR GRANT OF PERMISSION TO MANUFACTURE UNAPPROVED ACTIVE PHARMACEUTICAL INGREDIENT FOR DEVELOPMENT OF FORMULATION FOR TEST OR ANALYSIS OR CLINICAL TRIAL OR BIOAVAILABILITY OR BIOEQUIVALENCE STUDY", "CT-15", "PERMISSION TO MANUFACTURE UNAPPROVED ACTIVE PHARMACEUTICAL INGREDIENT FOR THE DEVELOPMENT OF FORMULATION FOR TEST OR ANALYSIS OR CLINICAL TRIAL OR BIOAVAILABILITY OR BIOEQUIVALENCE STUDY"],
          ["CT-16", "APPLICATION FOR GRANT OF LICENCE TO IMPORT NEW DRUG OR INVESTIGATIONAL NEW DRUG FOR CLINICAL TRIAL OR BIOAVAILABILITY OR BIOEQUIVALENCE STUDY OR FOR EXAMINATION, TEST AND ANALYSIS", "CT-17", "LICENCE TO IMPORT NEW DRUG OR INVESTIGATIONAL NEW DRUG FOR THE PURPOSE OF CLINICAL TRIAL OR BIOAVAILABILITY OR BIOEQUIVALENCE STUDY OR FOR EXAMINATION, TEST AND ANALYSIS"],
        ],
      },
  
      {
        title: "Importer’s Licences",
        rows: [
          ["CT-18", "APPLICATION FOR GRANT OF PERMISSION TO IMPORT NEW DRUG FOR SALE OR FOR DISTRIBUTION", "CT-19", "PERMISSION TO IMPORT NEW ACTIVE PHARMACEUTICAL INGREDIENT FOR SALE OR FOR DISTRIBUTION"],
          ["CT-18", "APPLICATION FOR GRANT OF PERMISSION TO IMPORT NEW DRUG FOR SALE OR FOR DISTRIBUTION", "CT-20", "PERMISSION TO IMPORT PHARMACEUTICAL FORMULATIONS OF NEW DRUG FOR SALE OR FOR DISTRIBUTION"],
          ["CT-24", "APPLICATION FOR LICENCE TO IMPORT OF UNAPPROVED NEW DRUG FOR TREATMENT OF PATIENTS OF LIFE THREATENING DISEASE IN A GOVERNMENT HOSPITAL OR GOVERNMENT MEDICAL INSTITUTION", "CT-25", "LICENCE TO IMPORT UNAPPROVED NEW DRUG FOR TREATMENT OF PATIENTS OF LIFE THREATENING DISEASE IN A GOVERNMENT HOSPITAL OR MEDICAL INSTITUTION"],
        ],
      },
  
      {
        title: "Manufacturer’s Licence",
        rows: [
          ["CT-21", "APPLICATION FOR GRANT OF PERMISSION TO MANUFACTURE NEW DRUG FORMULATION FOR SALE OR FOR DISTRIBUTION", "CT-22", "PERMISSION TO MANUFACTURE NEW ACTIVE PHARMACEUTICAL INGREDIENT FOR SALE OR FOR DISTRIBUTION"],
          ["CT-21", "APPLICATION FOR GRANT OF PERMISSION TO MANUFACTURE NEW DRUG FORMULATION FOR SALE OR FOR DISTRIBUTION", "CT-23", "PERMISSION TO MANUFACTURE PHARMACEUTICAL FORMULATION OF NEW DRUG FOR SALE OR FOR DISTRIBUTION"],
          ["CT-26", "APPLICATION FOR GRANT OF PERMISSION TO MANUFACTURE UNAPPROVED NEW DRUG BUT UNDER CLINICAL TRIAL FOR TREATMENT OF PATIENTS OF LIFE THREATENING DISEASE IN A GOVERNMENT HOSPITAL OR MEDICAL INSTITUTION", "CT-27", "PERMISSION TO MANUFACTURE UNAPPROVED NEW DRUG BUT UNDER CLINICAL TRIAL FOR TREATMENT OF PATIENTS OF LIFE THREATENING DISEASE IN A GOVERNMENT HOSPITAL OR MEDICAL INSTITUTION"],
        ],
      },
  
      {
        title: "Forms per Drugs and Cosmetics Act, 1940",
        rows: [
          ["Form 8", "Application For Licence To Import Drugs (Excluding Those Specified In Schedule X) To The Drugs And Cosmetics Rules, 1945", "Form 10", "Licence To Import Drugs (Excluding Those Specified In Schedule X) To The Drugs And Cosmetic Rules, 1945"],
          ["Form 8A", "Application For Licence To Import Drugs Specified In Schedule X To The Drugs And Cosmetics Rules, 1945", "Form 10A", "Licence To Import Drugs Specified In Schedule X To The Drugs And Cosmetics Rules, 1945"],
          ["Form 40", "Application To Import Drugs", "Form 41", "License To Import Drugs"],
        ],
      },
    ];
  
    return (
      <section className="py-10">
        <div className="container mx-auto px-4">
          
          {tableData.map((section, index) => (
            <div key={index} className="mb-10">
              <h2 className="text-2xl font-bold text-blue-700 mb-4">{section.title}</h2>
  
              <div className="overflow-x-auto border rounded-lg">
                <table className="w-full text-left border-collapse">
                  <thead className="bg-blue-50">
                    <tr>
                      <th className="p-3 border">Application Form Number</th>
                      <th className="p-3 border">Application Purpose</th>
                      <th className="p-3 border">Permission Form Number</th>
                      <th className="p-3 border">Permission Issued</th>
                    </tr>
                  </thead>
  
                  <tbody>
                    {section.rows.map((row, i) => (
                      <tr key={i} className="even:bg-gray-50">
                        <td className="p-3 border">{row[0]}</td>
                        <td className="p-3 border">{row[1]}</td>
                        <td className="p-3 border">{row[2]}</td>
                        <td className="p-3 border">{row[3]}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
  
            </div>
          ))}
  
        </div>
      </section>
    );
  }
  